In [5]:
#Import numpy library
import numpy as np
#create 1D numpy array
x = np.array([45,67,89,60])
print(x)
print(type(x))
print(x.dtype)

[45 67 89 60]
<class 'numpy.ndarray'>
int32


In [17]:
# Verify the date type
x = np.array(['A',67,89,60])
print(x)
print(type(x))
print(x.dtype)

['A' '67' '89' '60']
<class 'numpy.ndarray'>
<U11


In [13]:
#create 2D numpy array
x = np.array([[45,67],[89,60]])
print(x)
print(type(x))
print(x.shape)

[[45 67]
 [89 60]]
<class 'numpy.ndarray'>
(2, 2)


In [19]:
# Reshaping an array
a = np.array([10,20,30,40])
b = a.reshape(2,2)
print(b)
print(b.shape)

[[10 20]
 [30 40]]
(2, 2)


In [23]:
# Reshaping an array
a = np.array([10,20,30,40])
b = a.reshape(4,1)
print(b)
print(b.shape)

[[10]
 [20]
 [30]
 [40]]
(4, 1)


In [21]:
# create an array with arange()
c = np.arange(3,20)
print(c)
print(type(c))

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>


In [27]:
# Use of around()
d = np.array([1.34567, 3.103336, 4.288889])
print(d)
np.around(d,2)

[1.34567  3.103336 4.288889]


array([1.35, 3.1 , 4.29])

In [29]:
# Use of np.sqrt()
d = np.array([1.34567, 3.103336, 4.288889])
print(d)
print(np.around(np.sqrt(d),2))

[1.34567  3.103336 4.288889]
[1.16 1.76 2.07]


In [33]:
# 2D array
a1 = np.array([[3,4,5,6],[7,5,2, np.NAN]])
print(a1)
print(a1.dtype)
print(a1.shape)

[[ 3.  4.  5.  6.]
 [ 7.  5.  2. nan]]
float64
(2, 4)


In [19]:
# Mathamatical operations on rows and cols
a2 = np.array([[3,4,5],[6,8,7],[10,4,5]])
a2

array([[ 3,  4,  5],
       [ 6,  8,  7],
       [10,  4,  5]])

In [5]:
print(a2.sum(axis = 1))
print(a2.sum(axis = 0))

[12 21 19]
[19 16 17]


In [7]:
# Find mean value a long row and cols
print(a2)
print(a2.mean(axis = 1))
print(a2.mean(axis = 0))

[[ 3  4  5]
 [ 6  8  7]
 [10  4  5]]
[4.         7.         6.33333333]
[6.33333333 5.33333333 5.66666667]


In [9]:
#Matrix operations
a2 = np.array([[3,4,5],[6,8,7],[10,4,5]])
a2

array([[ 3,  4,  5],
       [ 6,  8,  7],
       [10,  4,  5]])

In [17]:
a2 = np.array([[3,4,5],[6,8,7],[10,4,5]])
print(a2)
np.fill_diagonal(a2,0)
print(a2)

[[ 3  4  5]
 [ 6  8  7]
 [10  4  5]]
[[ 0  4  5]
 [ 6  0  7]
 [10  4  0]]


In [35]:
# Accesing the array elements
a4 = np.array([[3,4,5],[6,8,7],[10,4,5],[10,9,18]])
print(a4)
print(a4[1][1])

[[ 3  4  5]
 [ 6  8  7]
 [10  4  5]
 [10  9 18]]
8
